### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by elythh** [cristiand391/zj-status-bar#3]
Hey ! That plugin looks really promising.
I just started using it and I was wondering how do you customize the look of bar in your Zellij config ? Since the default one doesn't look like [your screenshot](https://github.com/cristiand391/zj-status-bar/pull/2#issue-2274229068) and the config I found in your dotfiles seem to be default.

Thanks a lot !

**Comment by elythh** [comment]
Here's how it actually renders when having 2 tabs for example

![satty-20240502-16:17:27](https://github.com/cristiand391/zj-status-bar/assets/50964650/32020d19-d943-4e80-af93-edf6d225bfa9)

**Comment by cristiand391** [comment]
Hey @elythh , sorry for the late reply!

This plugin started as a fork of zelllij's compact-bar which isn't very configurable, I just added a few features on top of it (tab indexes, fullscreen indicator), see:
https://github.com/cristiand391/zj-status-bar/releases/tag/0.2.0

> the default one doesn't look like https://github.com/cristiand391/zj-status-bar/pull/2#issue-2274229068

I only have `[simplified_ui](https://zellij.dev/documentation/options#simplified_ui)` set to true.
There's no prerelease for tab notifications so you'll need to build it locally if you want  to try it.

I'll try to get some time this weekend to add a readme to the repo.

**Comment by elythh** [comment]
Hello @cristiand391, no worries about the last reply !

Thank you for the answer.
Indeed, I also thought it looked a lot like the compact bar haha. I see now !

Awesome, I might try to build master to test the tab notifications then.
